### ISSUE TITLE
Page 48-49 - Restarting after modifying Brocfile

### ISSUE THREAD

**Issue by stavarotti** [abuiles/ember-cli-101-errata#107]
Before or after the picnic installation steps , there is no mention of restarting the express server.  Changes made to Brocfile won't be applied until the next start of the express server.  

This is the line that may cause confusion as to why things are not working:

``` html
If we refresh our browser and go to http://localhost:4200/assets/vendor.css, we’ll see that the code
for picnicss is there.
```

**Comment by abuiles** [comment]
@stavarotti thanks!  I have changed that line as follows:

> After modifying our `Brocfile` we need to stop and start the server
> again so the changes are applied. Once we have done that, we can we
> refresh our browser and go to
> **http://localhost:4200/assets/vendor.css**, we'll see that the code
> for **picnicss** is there.

**Comment by simo163** [comment]
when I generate picninc with bower install it does not create the "bower_components/picnic/releases/v2.min.css" file... Any suggestions please?

When I run the server again it says:
```
Path or pattern "bower_components/picnic/releases/v2.min.css" did not match any files
Error: Path or pattern "bower_components/picnic/releases/v2.min.css" did not match any files
    at Object.multiGlob (/workspace/borrowers/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend._addFiles (/workspace/borrowers/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/simple-concat.js:82:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/workspace/borrowers/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/simple-concat.js:50:12)
    at /workspace/borrowers/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/workspace/borrowers/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/workspace/borrowers/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/workspace/borrowers/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/workspace/borrowers/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)

**Comment by abuiles** [comment]
Hey the issue is that they bump the version and didn't include the old one,
can you try doing the following in your brocfile.

app.import('bower_components/picnic/releases/latest.css');

## 

Adolfo Builes

**Comment by rabarar** [comment]
after bower installs picnic there is no file named **lastest.css** in the **releases** directory. 

I just added 
**app.import('bower_components/picnic/releases/picnic.min.css');**

**Comment by abuiles** [comment]
@rabarar until recently picnic had their version process broken, it means that it was fixed now :), I'll update this tomorrow.

**Comment by rabarar** [comment]
Cool. :)
