### ISSUE TITLE
Page 68: view Ember.Select deprecated, use view "select" instead

### ISSUE THREAD

**Issue by vais** [abuiles/ember-cli-101-errata#123]
The following line on page 68:

```
<td>{{view Ember.Select content=states selection=model.state}}</td>
```

produces a deprecation warning:

```
ember.js:15373 DEPRECATION: Resolved the view "Ember.Select" on the global context. Pass a view name to be looked up on the container instead, such as {{view "select"}}. http://emberjs.com/guides/deprecations#toc_global-lookup-of-views-since-1-8
        at lookupViewByClassName (http://localhost:4200/assets/vendor.js:20052:15)
        at handlebarsGetView (http://localhost:4200/assets/vendor.js:20100:23)
        at EmberObject.create.helper (http://localhost:4200/assets/vendor.js:22839:19)
        at viewHelper (http://localhost:4200/assets/vendor.js:23089:25)
        at program1 (http://localhost:4200/assets/borrowers.js:442:54)
        at prog (http://localhost:4200/assets/vendor.js:10933:14)
        at CoreView.extend.render (http://localhost:4200/assets/vendor.js:55511:20)
        at EmberRenderer_createElement [as createElement] (http://localhost:4200/assets/vendor.js:52738:16)
        at EmberRenderer.Renderer_renderTree [as renderTree] (http://localhost:4200/assets/vendor.js:23840:24)
```

Switching to using `<td>{{view "select" content=states selection=model.state}}</td>` works as expected without any warnings.

**Comment by tylergaw** [comment]
:+1:  on this. Page 68 just needs updated as Page 69 contains the correct usage that @vais mentioned.

**Comment by tylergaw** [comment]
The old `Ember.Select` shows up again on in "Working with JavaScript Plugins" on page 81:
`{{view Ember.Select content=states selection=model.state}}`

**Comment by abuiles** [comment]
Thanks! this has been fixed, will be available in the next release.
